name: Regression

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    types: [labeled]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda 
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: 3.9
    - name: Install lhapdf and PDFs
      shell: bash --login {0}
      run: |
        conda install gxx_linux-64 pkg-config sysroot_linux-64=2.17 numpy
        conda install -y lhapdf pineappl -c conda-forge
        lhapdf update
        lhapdf install NNPDF40_nnlo_as_01180
    - name: Compile vrap
      shell: bash --login {0}
      run: |
        cd src && autoreconf -fiv && cd ..
        mkdir -p build && cd build
        ../src/configure --prefix=/usr
        make -j4
        sudo make install
        Vrap ../regression_test/inputE605nlo.dat 7 0.2 # needs to have NNPDF40_nnlo_as_01180 installed
    - name: Run some cfactors
      if: contains(github.event.pull_request.labels.*.name, 'run-regression-test')
      shell: bash --login {0}
      run: |
        cd regression_test
        ./test_runer.sh
